### ISSUE TITLE
Allow html

### ISSUE THREAD

**Issue by ReportCardsMC** [IonicaBizau/ejs-playground#17]
Allow html so we can add buttons and such to the evaluated code.

**Comment by IonicaBizau** [comment]
What do you mean? Like, rendering the result as HTML?

**Comment by ReportCardsMC** [comment]
well I tried putting 
```html
<div class="btn">
  <button onclick="func()">Click</button>
</div>
```
And it doesn't work

**Comment by lcherone** [comment]
@RileyDatLord add special sauce

```
<%- eval(`document.write(\`

      <div class="btn">
        <button onclick="func()">Click</button>
      </div>

\`)`) %>
```

**Comment by IonicaBizau** [comment]
This is fixed now, just append `?html` in the url of the playground page.
