### ISSUE TITLE
Templates don't render anymore

### ISSUE THREAD

**Issue by Sogeman** [IonicaBizau/ejs-playground#19]
The Playground just stopped working from one second to the next for me.

All I get is a giant error 
`anonymous@https://npmcdn.com/ejs/ejs.min.js line 1 > Function:62:32
anonymous@https://npmcdn.com/ejs/ejs.min.js:1:9545
[1]</exports.render@https://npmcdn.com/ejs/ejs.min.js:1:4710
update@https://ionicabizau.github.io/ejs-playground/js/main.js:11:26
r._signal@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:50111
this.onDocumentChange@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:211902
r._signal@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:50111
this.onChange@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:153242
r._signal@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:50111
this.applyDelta@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:125633
this.insertMergedLines@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:123945
this.insert@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:122785
this.insert@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:161898
this.insert@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:216554
this.$handlePaste@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:215413
exec@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:194598
o/<@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:184317
r._dispatchEvent@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:49985
this.exec@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:184661
this.onPaste@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:215230
H@https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js:1:29570`

Edit: seems like it just doesn't work in Firefox. I forgot I switched to Firefox beforehand

**Comment by IonicaBizau** [comment]
Hmm, is this still an issue?
