### ISSUE TITLE
Add option to render the html

### ISSUE THREAD

**Issue by Sytten** [IonicaBizau/ejs-playground#23]
Hello! It would be cool if we could see the rendered HTML directly.
thanks

**Comment by Sytten** [comment]
Nvm it seems available, but it's really broken

**Comment by Sytten** [comment]
I see its because the body is ignored, it would better to put it inside an iframe

**Comment by IonicaBizau** [comment]
Just append the `?html` querystring in the URL.

**Comment by IonicaBizau** [comment]
Rendering it into an iframe could be a nice feature and make it more secure and stable. Contributions are welcome! ❇️

**Comment by Sytten** [comment]
Yeah because it messes up the CSS right now. I might do it if I have time.
