### ISSUE TITLE
EJS Version

### ISSUE THREAD

**Issue by RyanZim** [IonicaBizau/ejs-playground#4]
Is there a reason why this uses the old, unmaintained, EJS v1 (tj/ejs) instead of v2 (mde/ejs)? I was thinking maybe mde/ejs should link to this, but I see you're not using our version of the lib.

**Comment by IonicaBizau** [comment]
@RyanZim There is no specific reason. I coded this quite quickly to have a minimal app to play with. 😁 
Basically, this link should be changed: https://github.com/IonicaBizau/ejs-playground/blob/5ccc393850d331769955e1a3541432e840601cb8/index.html#L6

Linking it would be great! ✨

**Comment by RyanZim** [comment]
Yeah, should be https://npmcdn.com/ejs/ejs.min.js for the latest version (mde/ejs doesn't have the browser files in version control). Do you want to fix this yourself or should I submit a PR?

**Comment by IonicaBizau** [comment]
@RyanZim If you can fix it, that would be great! ✨

**Comment by RyanZim** [comment]
@IonicaBizau 

> Linking it would be great!

I've been wanting to do this but don't get time. Perhaps you could submit a PR to mde/ejs yourself? Feel free to mention me.

**Comment by IonicaBizau** [comment]
@RyanZim I was just busy with random projects, is it possible to do it for me? 😁

**Comment by RyanZim** [comment]
:laughing: Perhaps; I was just busy with random projects.

**Comment by IonicaBizau** [comment]
😁

**Comment by RyanZim** [comment]
BTW, Here's my latest time-consumer: https://github.com/RyanZim/onessg.
